"use client";

import { motion } from "framer-motion";
import { 
  Flame, 
  Search, 
  Award, 
  CheckCircle, 
  ExternalLink, 
  HelpCircle,
  TrendingUp,
  Loader2,
  Clock
} from "lucide-react";
import { GlassCard } from "@/components/ui/GlassCard";

export interface CctpTxState {
  isActive: boolean;
  sourceChain: string;
  destChain: string;
  amount?: string | number;
  currentStep: "idle" | "burn" | "attestation" | "received" | "mint" | "success" | "error";
  burnTxHash?: string;
  mintTxHash?: string;
  elapsedSeconds?: number;
  errorMessage?: string;
}

export function CctpStepVisualizer({ txState }: { txState: CctpTxState }) {
  const {
    isActive,
    sourceChain,
    destChain,
    amount,
    currentStep,
    burnTxHash,
    mintTxHash,
    elapsedSeconds = 0,
    errorMessage
  } = txState;

  // Determine step status
  const getStepStatus = (stepIndex: number) => {
    // Indices:
    // 0 = Burn on Source
    // 1 = Poll Attestation
    // 2 = Attestation Received
    // 3 = Mint on Destination
    
    if (currentStep === "error") {
      return "error";
    }

    if (currentStep === "success") {
      return "completed";
    }

    switch (stepIndex) {
      case 0: // Burn
        if (currentStep === "idle") return "idle";
        return (currentStep === "burn") ? "active" : "completed";
        
      case 1: // Attestation
        if (currentStep === "idle" || currentStep === "burn") return "idle";
        return (currentStep === "attestation") ? "active" : "completed";
        
      case 2: // Received
        if (currentStep === "idle" || currentStep === "burn" || currentStep === "attestation") return "idle";
        return (currentStep === "mint") ? "completed" : "idle";
        
      case 3: // Mint
        return (currentStep === "mint") ? "active" : "idle";
        
      default:
        return "idle";
    }
  };

  const getChainExplorerLink = (chainName: string, txHash: string) => {
    const lower = chainName.toLowerCase();
    if (lower.includes("sepolia") && lower.includes("ethereum")) {
      return `https://sepolia.etherscan.io/tx/${txHash}`;
    }
    if (lower.includes("sepolia") && lower.includes("base")) {
      return `https://sepolia.basescan.org/tx/${txHash}`;
    }
    if (lower.includes("fuji") || lower.includes("avalanche")) {
      return `https://testnet.snowtrace.io/tx/${txHash}`;
    }
    return `https://testnet.arcscan.app/tx/${txHash}`;
  };

  const steps = [
    {
      title: "Burn USDC on Source",
      description: `Initiate burn on ${sourceChain}`,
      icon: Flame,
      color: "text-red-400",
      activeColor: "bg-red-500/10 border-red-500/30 text-red-400",
      txHash: burnTxHash,
      chain: sourceChain
    },
    {
      title: "Circle Consensus Attestation",
      description: "Polling Circle Sandbox Iris API",
      icon: Search,
      color: "text-purple-400",
      activeColor: "bg-purple-500/10 border-purple-500/30 text-purple-400",
      isAttestation: true
    },
    {
      title: "Attestation Signed & Received",
      description: "Cryptographic proof generated by Circle",
      icon: Award,
      color: "text-yellow-400",
      activeColor: "bg-yellow-500/10 border-yellow-500/30 text-yellow-400"
    },
    {
      title: "Mint USDC on Destination",
      description: `Complete mint on ${destChain}`,
      icon: CheckCircle,
      color: "text-blue-400",
      activeColor: "bg-blue-500/10 border-blue-500/30 text-blue-400",
      txHash: mintTxHash || (currentStep === "success" ? mintTxHash : undefined),
      chain: destChain
    }
  ];

  if (!isActive) {
    return null;
  }

  // ──── ACTIVE STATE VISUALIZER ────
  const activeStepIndex = 
    currentStep === "burn" ? 0 : 
    currentStep === "attestation" ? 1 : 
    currentStep === "mint" ? 3 : 
    currentStep === "success" ? 4 : 0;

  return (
    <GlassCard className="p-5 border-primary/20 bg-gradient-to-br from-primary/[0.01] to-transparent text-left space-y-4 shadow-[0_0_30px_rgba(168,85,247,0.03)]" hover={false}>
      <div className="flex items-center gap-2">
        <TrendingUp className="w-5 h-5 text-primary animate-pulse" />
        <h2 className="text-sm font-bold text-text-primary">
          CCTP Transfer Progress
          {amount && <span className="font-mono text-primary ml-1.5">({amount} USDC)</span>}
        </h2>
        <span className="ml-auto text-[9px] font-extrabold px-1.5 py-0.5 rounded bg-primary/20 text-primary border border-primary/30 uppercase tracking-widest animate-pulse">
          Live Polling
        </span>
      </div>

      {currentStep === "error" && errorMessage && (
        <div className="p-3.5 bg-danger/10 border border-danger/20 rounded-xl text-xs text-danger flex items-start gap-2">
          <HelpCircle className="w-4 h-4 shrink-0 mt-0.5" />
          <div className="break-words font-medium">{errorMessage}</div>
        </div>
      )}

      {/* Progress Bar */}
      <div className="space-y-1">
        <div className="flex justify-between items-center text-[10px] text-text-tertiary font-mono">
          <span>Bridge Pipeline Status</span>
          <span className="font-bold">
            {currentStep === "success" ? "100% - SUCCESS" : 
             currentStep === "mint" ? "85% - MINTING" :
             currentStep === "attestation" ? `60% - ATTESTING (${elapsedSeconds}s)` :
             currentStep === "burn" ? "25% - BURNING" : "0%"}
          </span>
        </div>
        <div className="h-1.5 bg-surface rounded-full overflow-hidden border border-border-thin/40">
          <motion.div 
            className="h-full bg-gradient-to-r from-red-500 via-purple-500 to-blue-500 rounded-full"
            initial={{ width: "0%" }}
            animate={{ 
              width: currentStep === "success" ? "100%" : 
                     currentStep === "mint" ? "85%" : 
                     currentStep === "attestation" ? "60%" : 
                     currentStep === "burn" ? "25%" : "0%"
            }}
            transition={{ duration: 0.5 }}
          />
        </div>
      </div>

      {/* Visual Timeline Steps */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-3.5">
        {steps.map((step, idx) => {
          const Icon = step.icon;
          const status = getStepStatus(idx);
          const isCompleted = status === "completed";
          const isActiveStep = status === "active";
          const isPending = status === "idle";

          return (
            <div 
              key={idx}
              className={`p-3.5 rounded-xl border transition-all duration-500 flex flex-col gap-3 relative overflow-hidden ${
                isActiveStep 
                  ? `${step.activeColor} shadow-[0_0_15px_rgba(168,85,247,0.08)]` 
                  : isCompleted 
                  ? "bg-success/5 border-success/20 text-muted" 
                  : "bg-surface-elevated/40 border-border-thin text-text-tertiary opacity-60"
              }`}
            >
              {/* Highlight background glow on active */}
              {isActiveStep && (
                <div className="absolute top-0 right-0 w-12 h-12 bg-primary/5 rounded-full blur-xl animate-pulse pointer-events-none" />
              )}

              <div className="flex items-center justify-between">
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center border transition-all duration-500 ${
                  isActiveStep 
                    ? "bg-white-keep text-black font-bold scale-105" 
                    : isCompleted 
                    ? "bg-success/15 border-success/30 text-success" 
                    : "bg-surface border-border-thin"
                }`}>
                  {isActiveStep && step.isAttestation ? (
                    <Loader2 className="w-4 h-4 animate-spin text-purple-400" />
                  ) : (
                    <Icon className="w-4 h-4" />
                  )}
                </div>
                
                <span className={`text-[10px] font-bold font-mono ${
                  isActiveStep ? "text-text-primary" : isCompleted ? "text-success" : "text-text-tertiary"
                }`}>
                  {isCompleted ? "✓ Done" : isActiveStep ? "Active" : `0${idx + 1}`}
                </span>
              </div>

              <div>
                <h4 className={`text-[11px] font-bold leading-tight ${
                  isActiveStep ? "text-text-primary" : isCompleted ? "text-muted" : "text-text-tertiary"
                }`}>{step.title}</h4>
                <p className="text-[9px] text-text-tertiary leading-snug mt-0.5">{step.description}</p>
              </div>

              {/* Extra Polling Details */}
              {isActiveStep && step.isAttestation && (
                <div className="text-[9px] font-mono text-purple-300 flex items-center gap-1 mt-1 border-t border-purple-500/10 pt-1.5">
                  <Clock className="w-2.5 h-2.5 animate-pulse" />
                  <span>Polling: {elapsedSeconds}s</span>
                </div>
              )}

              {/* Tx Hash Link */}
              {step.txHash && (
                <div className="mt-1 border-t border-border-thin/40 pt-1.5 flex flex-col gap-0.5">
                  <span className="text-[8px] text-text-tertiary uppercase tracking-wider block font-bold">Transaction</span>
                  <a 
                    href={getChainExplorerLink(step.chain || "", step.txHash)}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-[9px] font-mono font-bold text-primary hover:underline flex items-center gap-0.5"
                  >
                    <span>{step.txHash.slice(0, 6)}...{step.txHash.slice(-4)}</span>
                    <ExternalLink className="w-2.5 h-2.5" />
                  </a>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </GlassCard>
  );
}
